version: 0.0
os: linux
files:
   - source: /
     destination: /var/www/html/magento-community-aws/
permissions:
   - object: /var/www/html/magento-community-aws/
     owner: ubuntu
     group: www-data
     mode: 775
     type:
       - file
       - directory
hooks:
   BeforeInstall:
    - location: scripts/stopapache.sh
      runas: root
   AfterInstall:
    - location: scripts/startapache.sh
      runas: root
